### ISSUE TITLE
Multi monitor

### ISSUE THREAD

**Issue by z2i** [PRATAP-KUMAR/ubuntu-gdm-set-background#11]
Hello.
Thank you for this wonderful script.

On Ubuntu 22.04 setted background being stretched between two monitors.
Any way how it can be fixed? so, to have one image per monitor.
Thnx in advance

**Comment by PRATAP-KUMAR** [comment]
Hi, for 22.04 or for some previous versions of Ubuntu.. this script is no more needed.
the question you have raised is a long back one and has a workaround. I will share you links in the next comment.

**Comment by PRATAP-KUMAR** [comment]
https://github.com/thiggy01/change-gdm-background/issues/15#issuecomment-719942970

https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/issues/9

**Comment by z2i** [comment]
Thank you!
Advices from the link worked.

**Comment by r0ei** [comment]
On Ubuntu 20.04.4 non of the above solutions work. The image is still stretched on login screen.
