### ISSUE TITLE
Ubuntu 22.04.1 LTS update doesn't work

### ISSUE THREAD

**Issue by Bob19555** [PRATAP-KUMAR/ubuntu-gdm-set-background#14]
Hi, After updating to Ubuntu 22.04.1 LTS using the GDM background crashes my session with the warning; oh something went wrong etc.. (white screen). I'm able to go in tty6 but my regular session on tty7 is now blocked. What can I do to resolve this problem??

Thanks in advance!

**Comment by PRATAP-KUMAR** [comment]
Hi plz uninstall this extension and use the built in method to tweak GDM

**Comment by Bob19555** [comment]
Hi! Thanks for replying so quickly! I'll will do so!Bob

Verzonden vanuit de geheel nieuwe AOL-app voor Android 
 
  Op ma, aug. 15, 2022 om 18:52 schreef PRATAP ***@***.***>:   


Hi plz uninstall this extension and use the built in method to tweak GDM
