### ISSUE TITLE
Not Supported for Ubuntu 22.10

### ISSUE THREAD

**Issue by dipeshsingh253** [PRATAP-KUMAR/ubuntu-gdm-set-background#18]
I have tried to run the script on Ubuntu 22.10 :

![image](https://user-images.githubusercontent.com/84814627/200302337-59854f6f-7b76-4929-9201-68d47c1c06ba.png)

**Comment by PRATAP-KUMAR** [comment]
Can you try with absolute path as parameter please

**Comment by dipeshsingh253** [comment]
I have tried it with absolute path but output is still same.

**Comment by PRATAP-KUMAR** [comment]
Can we meet via zoom?

**Comment by dipeshsingh253** [comment]
Yeah sure whenever you want...

**Comment by PRATAP-KUMAR** [comment]
Send me zoom link, will join in 5mins

**Comment by dipeshsingh253** [comment]
https://us06web.zoom.us/j/85696492319?pwd=QkVQT2R4TWtjSVRFYUhJMUdXVThOQT09 

here..

**Comment by dipeshsingh253** [comment]
Still not changed.. 😅

**Comment by PRATAP-KUMAR** [comment]
Hi for Ubuntu 22.04 and onwards there is no need for any script. Ubuntu providing the command line way https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/issues/9

**Comment by PRATAP-KUMAR** [comment]
Ok, check this one https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/issues/17

I will schedule another zoom meeting if the above one not working later

**Comment by dipeshsingh253** [comment]
Okay I will update it.

**Comment by dipeshsingh253** [comment]
[ChunkyZacko5](https://github.com/ChunkyZacko5)
s solution #17 
![image](https://user-images.githubusercontent.com/84814627/200465171-e9db9690-ad45-42a4-ae19-c464af882faa.png)
I have edited the shell file as in the above image.
When I run the script it goes well without any error but when I restart the login background is changed to blue color as shown in the image below.
![1667876789408](https://user-images.githubusercontent.com/84814627/200465532-ce7cd531-94da-4ae7-8f33-c707238275e1.jpg)

**Comment by PRATAP-KUMAR** [comment]
Ok that means script is working n taking default color. I will get back to you at 11am or 11:30

**Comment by dipeshsingh253** [comment]
Fine
