### ISSUE TITLE
Image distributed along screens, no option to repeat the image

### ISSUE THREAD

**Issue by Tom743** [PRATAP-KUMAR/ubuntu-gdm-set-background#2]
When running`sudo ./ubuntu-gdm-set-background --image /home/tomas/Pictures/wallpapers/beautiful-snowy-mountain-d85z0rzrlddaylao.jpg` the image is set as login background, but I only see the middle left quarter of the image on my left screen and the middle right quarter on the right screen, at low resolution.
I have a dual 1080p monitor setup side by side, and the image is **(not)** 1920x1080 **edit: I just realised it is 3648x2432 pixels, but when using one screen only I see the full image, not a 1080p zoom in**. I want to be able to see the full image on both screens. It looks fine when using only one monitor.
How can this be improved to give the option to show the image separately on different displays?

The image I want as a backgound:
![beautiful-snowy-mountain-d85z0rzrlddaylao](https://user-images.githubusercontent.com/41840767/139586684-a4172eab-ef9a-43d3-9498-a253ed92dbd8.jpg)

What I see with two screens:
![20211031_104937](https://user-images.githubusercontent.com/41840767/139587030-f89621aa-b1cc-404c-9202-453b4a2372f2.jpg)

When only using one display (and how I'd like it to look on all of my screens):
![20211031_104942](https://user-images.githubusercontent.com/41840767/139587153-90a1bd3b-e859-461b-9bac-a9dcf63ab55d.jpg)

**Comment by PRATAP-KUMAR** [comment]
Hi..
Can you go through this post and revert back.
https://github.com/PRATAP-KUMAR/focalgdm3/issues/2

**Comment by Tom743** [comment]
Hi. Tanks for your answer, but I don't want to reverse the changes, I wanted to have the image repeated on both screens. I saw there is a similar issue, and the descripted workaround was creating an image that contains both images, which is probably what I'll do if I ever try again

Good tool though, the login screen looks much better with a background image

**Comment by mendhak** [comment]
I think there's a way to do this, from an issue on a similar script repo:  https://github.com/thiggy01/change-gdm-background/issues/15#issuecomment-719942970

The gist you'll see there, is you create a `monitors.xml` that mirrors your monitors. Then copy it to the GDM user's directory.  (Then reset your own display configuration ofcourse).  Then set the GDM's wallpaper with this script.

**Comment by mahtamun-hoque-fahim** [comment]
Hello @PRATAP-KUMAR  !!
Seems like running this script slowed down the speed of my PC while opening.
Can I undo what I did?
I mean can I revert to where it was?
to purplish-pink default ubuntu login screen ?

**Comment by PRATAP-KUMAR** [comment]
Yes.
`sudo ./ubuntu-gdm-set-background --reset`

**Comment by mahtamun-hoque-fahim** [comment]
> Yes. `sudo ./ubuntu-gdm-set-background --reset`

Thank you souuuuuuuuuuuuuu much !
