### ISSUE TITLE
Support to the Indian distro Ubuntu Cinnamon Remix (should also cover Linux Mint as courtesy)

### ISSUE THREAD

**Issue by danimesq** [PRATAP-KUMAR/ubuntu-gdm-set-background#20]

**Comment by PRATAP-KUMAR** [comment]
Hi @danimesq does Ubuntu Cinnamon Remix also uses gdm? are you working on this?

**Comment by danimesq** [comment]
Ubuntu Cinnamon Remix uses Cinnamon, which is a fork of the old Gnome.

Probably it uses lightdm instead of gdm.

And yes, I have to work on this because my distro is based in UCR and I don't want to reveal the user's background right on the login when any stranger can see (so I think there's a reason why our phones have a difference between launcher and lockscreen backgrounds so I want to follow it).

**Comment by PRATAP-KUMAR** [comment]
Hi @danimesq if it uses lightdm then there is no need to continue with this repo rite as it deals with gdm?

**Comment by danimesq** [comment]
Or, if you would like to, expand this repo's purpose.

In case of a negative, we (or me only) could make a more general repo that leverages ubuntu-gdm-set-background alongside other functions to support other DEs such as Cinnamon.
What do you think about?
