### ISSUE TITLE
Lock screen blur

### ISSUE THREAD

**Issue by AlistairTB** [PRATAP-KUMAR/ubuntu-gdm-set-background#21]
Is it possible to disable to lock screen blur?

**Comment by PRATAP-KUMAR** [comment]
Hi, @AlistairTB there is an extension that makes it possible.  Have a look at it.
https://extensions.gnome.org/extension/2935/control-blur-effect-on-lock-screen/

**Comment by AlistairTB** [comment]
I just found and tried installing that extension, but it appears it doesn't work for Gnome shell 43.1. It looks like it only supports 42.

`
$ gnome-shell --version
GNOME Shell 43.1
`

![Screenshot from 2023-02-14 08-51-33](https://user-images.githubusercontent.com/89739791/218757994-40d1217e-cc6c-41ba-8d0a-351bb54261d0.png)

**Comment by PRATAP-KUMAR** [comment]
Oh yes.. I have to push it to gnome-extensions.. can you download the zip file from comments. If you can download thats fine. Otherwise wait for some days as I am planning to upload it to gnome-extensions

**Comment by PRATAP-KUMAR** [comment]
Hi @AlistairTB It is available now from gnome-extensions, can you try it now, please?

**Comment by AlistairTB** [comment]
No effect.

`
$ gnome-extensions list
ControlBlurEffectOnLockScreen@pratap.fastmail.fm

$ sha256sum metadata.json 
3e8dd28d14d113514ebd7efa340a8b395b963c249e45760678c62adbf9be3a9e  metadata.json
`
When I lock screen and log back in, wallpaper is still blurred.

**Comment by PRATAP-KUMAR** [comment]
Hi, can we have a quick zoom call, is it ok for you?

**Comment by AlistairTB** [comment]
Can you do Wire video call? http://app.wire.com/

**Comment by PRATAP-KUMAR** [comment]
Hi, I am installing it, once installed, how can I call you.. I am ready to call you

**Comment by AlistairTB** [comment]
I will need to know your user name to connect with you.

**Comment by PRATAP-KUMAR** [comment]
it is PRATAP-KUMAR

**Comment by AlistairTB** [comment]
Solution was to enable the extension!

```$ gnome-extensions enable ControlBlurEffectOnLockScreen@pratap.fastmail.fm```

**Comment by AlistairTB** [comment]
Thank you so much for your accurate and engaging support!
