### ISSUE TITLE
Ubuntu 23.04 support with a twist

### ISSUE THREAD

**Issue by berglh** [PRATAP-KUMAR/ubuntu-gdm-set-background#23]
I tried to override this script to use on lunar (23.04), however it didn't produce the desired results.

I will add an exception though, it may have applied correctly, however, the GDM greeter seems to have a hardcoded top-level colour and an extremely high alpha value of 0.975 from my initial looks.

I tried to use the method described here: [https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1929536](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1929536)

It turns out the image in the above `gsettings` method is applied, but the overlay colour dominates the background image completely so that you can barely see it.

I tried to manually edit these values in `/usr/share/gnome-shell/gdm-theme.gresource` in the `lockDialogGroup` to set an extremely low alpha value, but it didn't seem to have any impact on the display of the image at all.

```diff
#lockDialogGroup {   
-  background-color: rgba(29, 29, 29, 0.975); }
+  background-color: rgba(29, 29, 29, 0.001); }
```

I did notice that there were 22 instances of lockDialogGroup in the default `gdm-theme.gresource`, I tried to change all of them, all without effect directly in the file. I'm guessing this is the cause and that I probably need to use `glib-compile-resources` to get it to function correctly.

**Comment by PRATAP-KUMAR** [comment]
Hi @berglh I will try to figure it out and get back to you today either with success or failure.

Thanks
PRATAP

**Comment by PRATAP-KUMAR** [comment]
Hi @berglh I was trying yesterday and my Ubuntu 23.04 have some issues before trying this. I may have to reinstall 23.04 this weekend. Sorry for the delay.

Thanks
PRATAP

**Comment by berglh** [comment]
@PRATAP-KUMAR No problems, good luck - let me know if there is anything you'd like me to test.

**Comment by PRATAP-KUMAR** [comment]
@berglh the major difference is that `#lockDialogGroup` -> `.login-dialog` and `gdm3-theme.gresource -> gdm-theme.gresource`.

I have uploaded the file `ubuntu-gdm-set-background-23.04` in the main branch. you can test it.
the above script directly sets the background image or color as in the previous versions but since we have `gsettings` key for background settings, I am testing it to change the transparency or opacity with this script. I will update you tomorrow. But for now the script works.

Its been fullday I was struggling to find that said change. Tired.

Thanks

**Comment by PRATAP-KUMAR** [comment]
@berglh @kirkog86 Its done now. Setting the login-background to transparent with the script `ubuntu-gdm-set-background-23.04-transparent` and then setting the background with gsettings (https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1929536) is the recommonded way.  Can you check and comment please.

Thanks
PRATAP

**Comment by berglh** [comment]
Hi @PRATAP-KUMAR,

Your script is working for me. Looking at your code, I wondered if the background-color setting exposed by `gsettings` under `gdm` would work with the transparent setting you apply:

```bash
gdm@zen:~$ gsettings list-keys com.ubuntu.login-screen 
background-color
background-picture-uri
background-repeat
background-size
```
However, setting `background-color` here as transparent doesn't appear to affect the gdm greeter. If the background is able to be set by `gsettings`, one wonders if this is a bug in implementation of `background-color`. I see the schema you apply the configuration to is org.gnome.shell.theme, and this doesn't appear to be exposed via `gsettings`.

Anyway, many thanks for your hard work in figuring this one out, all is well with my greeter screen 🙏

**Comment by berglh** [comment]
@PRATAP-KUMAR I've opened a bug in the Ubuntu gnome-shell repository with respect to this: [https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/2018672](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/2018672) If anyone interested in this being correctly supported via `gsettings` should click "This affects me too link" at the top of the of the bug report page.
