### ISSUE TITLE
Ubuntu 23.04 - Why Does It Create a Grey Fade (see Screencast)

### ISSUE THREAD

**Issue by amiga-500** [PRATAP-KUMAR/ubuntu-gdm-set-background#25]
I have never seen this problem before until now.  I used your tool to change my login background to black.  As u can see in the animation it worked!  But it now also includes a grey fade before the login and right after i enter the password to login.  

How do i stop that animation and for that matter get rid of the grey?

I dont have animation turned on via Accesibility  (it is set to "Reduce Animation").  Also

org.gnome.desktop.interface enable-animations = false

Prior to using ur tool on a fresh 23.04 i did not see any grey fade.  It seem to occur after i used your tool.  Also when i use "--reset" it resets to a grey background and the fade still remains.

![sss](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/assets/5191497/718386f0-1eb9-491b-a0b8-416baa7fd7ed)

**Comment by PRATAP-KUMAR** [comment]
Hi, Sorry to hear about the issue.
Quick question, which script did you use?
![image](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/assets/40719899/e2b897f4-8845-423c-a55e-7c179c73f060)

**Comment by amiga-500** [comment]
Hi there..Wow youa are quick!  I used the 2nd last: `ubuntu-gdm-set-background-23.04`

**Comment by PRATAP-KUMAR** [comment]
Hi, from your video, you used ubuntu-gdm-set-background it seems, let me see again

**Comment by amiga-500** [comment]
Ahh..let me give u the code...or i will go do a compare....I am hoping i did use the wrong one then :)  (gives me hope)

**Comment by PRATAP-KUMAR** [comment]
Ok, first do one thing..
use the same scrpt `ubuntu-gdm-set-background` with --reset option and check if everything is normal.
Then we can dive into next steps to solve the issue.

**Comment by amiga-500** [comment]
Ok i downloaded ur ubuntu-gdm-set-background but because i am using 23.04 it shows this:

![image](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/assets/5191497/da2158fc-22aa-4e28-9f39-ffb62e43c2aa)

**Comment by PRATAP-KUMAR** [comment]
wait, in your first video you ran `ubuntu-gdm-set-background`. you said you tried --rest rite, can you do the same thing again with the same script. we are trying to rest to normal with the same script first.

If things are messed up,
do this command
`apt install --reinstall yaru-theme-gnome-shell`

**Comment by amiga-500** [comment]
Oh sorry i misread ur line thought u meant to use the old script.
apologies

**Comment by PRATAP-KUMAR** [comment]
yes with the old script, reset it and check if the gdm turns to normal, then we can go for next steps.

**Comment by amiga-500** [comment]
Ok i reset it.  
![image](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/assets/5191497/792f7972-cd47-46e2-a80d-cf787f75ec70)

I also logged out and my screen is now grey.  I figure this means its all reset.  All looks fine.

**Comment by PRATAP-KUMAR** [comment]
Thats a great thing.
Now can you read the readme file about `ubuntu-gdm-set-background-23.04-transparent`

**Comment by amiga-500** [comment]
Ok reading now.

**Comment by PRATAP-KUMAR** [comment]
Try this way and then we will see about grey

> ubuntu-gdm-set-background-23.04-transparent -> sets the login-background color transparent so that the background set via gsettings set com.ubuntu.login-screen background-picture-uri is visible. This is the RECOMMENDED way.
> Please follow this link for setting login background via gsettings: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1929536
> 
> [Test Case]
> 
> Boot a desktop session
> Verify that the greeter shows the default aubergine background.
> Login as the administrator of the machine
> Install systemd-container
> Switch to the GDM user: $ sudo machinectl shell gdm@ /bin/bash
> Apply a different background with the command: $ gsettings set com.ubuntu.login-screen background-picture-uri 'file:///usr/share/backgrounds/warty-final-ubuntu.png'
> Logout
> Verify that the greeter now shows the image warty-final-ubuntu.png.

**Comment by amiga-500** [comment]
Ok followed the steps above and it now shows

![image](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/assets/5191497/05cb0b00-27d5-4b23-85a7-043401a648ce)

**Comment by PRATAP-KUMAR** [comment]
Hi did you set the login background to an image or black? did you follow that machinectl command?

**Comment by amiga-500** [comment]
oh i followed the steps exactly as posted above so including the image.
so my steps were:

1. Login as the administrator of the machine
2. sudo apt installl systemd-container
3. sudo machinectl shell gdm@ /bin/bash
4. gsettings set com.ubuntu.login-screen background-picture-uri 'file:///usr/share/backgrounds/warty-final-ubuntu.png'
5. Logout

And then i took a snap to post here

**Comment by PRATAP-KUMAR** [comment]
did you logout and log in to see?

**Comment by amiga-500** [comment]
![sss](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/assets/5191497/b292a122-d7e8-4fbc-a9f1-fdcb58535507)

**Comment by PRATAP-KUMAR** [comment]
great, now run ubuntu-transparent script now

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/issues/23 this issue will be helpful to understand what is happening.

Thanks

**Comment by amiga-500** [comment]
Thanks very much.  It seemed to help but since i dont want that image in the background i tried to remove it by doing the steps again as machinectl so i can set the picture-uri to '' but when i do the grey returns.  So does this mean i have to use a background image no matter what and i cannot have it as just plain black?
