### ISSUE TITLE
This plugin does not work with GNOME4

### ISSUE THREAD

**Issue by xpww** [PRATAP-KUMAR/ubuntu-gdm-set-background#26]
In order to try the new features of gnome, I upgraded my gnome on ubuntu to gnome41. However, after the upgrade, I found that using the instructions given by the author could not replace the background of the login interface. It would prompt that some files of gnome3 were lost. However, in fact I am using gnome4

**Comment by PRATAP-KUMAR** [comment]
Hi can you try this way https://askubuntu.com/a/1396066/739431
