### ISSUE TITLE
No work use super+L lockscreen

### ISSUE THREAD

**Issue by 11wanqin** [PRATAP-KUMAR/ubuntu-gdm-set-background#27]
CTRL+ALT+F1  can show the change image,
but super+L  not show the change image,
I have reboot .
how can i solve the program.

**Comment by PRATAP-KUMAR** [comment]
Hi, Super L is for screen lock and it is not related to the script.
You can look for lock screen background extension https://extensions.gnome.org/extension/1476/unlock-dialog-background/

Thanks

**Comment by 11wanqin** [comment]
thank you.
