### ISSUE TITLE
absolute path to image is neither provided nor it is valid.

### ISSUE THREAD

**Issue by 3diamond** [PRATAP-KUMAR/ubuntu-gdm-set-background#3]
Hi I get this message
absolute path to image is neither provided nor it is valid.
see help with below command
./ubuntu-gdm-set-background --help

when using"sudo ./ubuntu-gdm-set-background --image /home/picture/image.jpg"

using 
ubuntu 21.10
gnome 40.4.0

**Comment by PRATAP-KUMAR** [comment]
Hi,
I guess /home/_username_/Pictures/image.jpg should be the one you need to provide. what is the output of `$HOME/Pictures`

**Comment by 3diamond** [comment]
Hi,
its:
/usr/share/backgrounds/image.jpg
all working now.
Thanks
