### ISSUE TITLE
23.04 has 'lunar' codename

### ISSUE THREAD

**Issue by EmilPosmyk** [PRATAP-KUMAR/ubuntu-gdm-set-background#35]
Please check codename and change it if necessary to use the script in Ubuntu 23.04. Seems it's incorrect (should be lunar).
thank you

**Comment by danimesq** [comment]
@EmilPosmyk
Hopefully fixed at https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/pull/37/commits/d8aa2afed48ddcd2346103407c3f8cac9b00611a.

**Comment by danimesq** [comment]
@EmilPosmyk, sorry for the ping twice. Can you please confirm the issue was fixed?

On your cloned repo, just do "git pull", then try again; if working now, please tell here.

**Comment by EmilPosmyk** [comment]
if I change it to: 
`if [[ "$codename" =~ ^(lunar|mantic)$ && "$osname" == \"Ubuntu\" ]]; then`
then it works :-)

Seems \"Ubuntu\" is then correctly interpreted. I guess it should be changed in all places also.

**Comment by danimesq** [comment]
@EmilPosmyk thank you! Could you please attach your modified files?

**Comment by EmilPosmyk** [comment]
I'm sorry. I overlooked somehow your message. I just noticed it when checking my data on github. Anyway late but still if it is useful for anyone :-) Whole source of the file 'ubuntu-gdm-set-background'
`#!/bin/bash

#Cursor GPT prompt:
#Please do any improvement you find fit.
#
#Please comment (#) in the end what was changed and why it is better.
#
#Please don't change the color names.

# Colors
Red='\e[0;31m'  # Kept color names as requested
BRed='\e[1;31m'  # Kept color names as requested
BIRed='\e[1;91m'  # Kept color names as requested
Gre='\e[0;32m'  # Kept color names as requested
BGre='\e[1;32m'  # Kept color names as requested
BBlu='\e[1;34m'  # Kept color names as requested
BWhi='\e[1;37m'  # Kept color names as requested
RCol='\e[0m'  # Kept color names as requested

codename="$(grep UBUNTU_CODENAME /etc/os-release | cut -d = -f 2)"
osname="$(grep -E '="?Ubuntu"?$' /etc/os-release | cut -d = -f 2)"
#echo -e $codename
#echo -e $osname

if [[ "$codename" =~ ^(focal|hirsute|impish|jammy|kinetic)$ && "$osname" == \"Ubuntu\" ]]; then  # Changed the condition for better readability
  bash src/pre-23.sh "$@"  # Changed to use double quotes for consistency
fi

if [[ "$codename" =~ ^(lunar|mantic)$ && "$osname" == \"Ubuntu\" ]]; then
  bash src/post-23.sh "$@"  # Changed to use double quotes for consistency
fi

if [[ "$codename" =~ ^(focal|hirsute|impish|jammy|kinetic|lunar|mantic)$ && "$osname" == \"Ubuntu\" ]]; then  # Changed the condition for better readability
: #no-op cmd, thanks to https://stackoverflow.com/a/17583599
else
  echo -e "${Red}
------------------------------------------------------------------
Sorry, Script is only for Ubuntu ${BWhi}20.04, 21.04, 21.10, 22.04, 22.10, 23.04 & 23.10${Red} Only
Exiting...
------------------------------------------------------------------${RCol}"
  exit 1
fi`
