### ISSUE TITLE
Error in Ubuntu 22 LTS

### ISSUE THREAD

**Issue by in4matix** [PRATAP-KUMAR/ubuntu-gdm-set-background#38]
Was working before, but now:

```
daniel@dkdt:~/Store/Customization/GdmScript/ubuntu-gdm-set-background/ubuntu-gdm-set-background$ sudo bash ubuntu-gdm-set-background image /home/daniel/Store/Customization/GdmScript/GdmWP/gdm-20.jpg rescue
[sudo] password for daniel: 

------------------------------------------------------------------
Sorry, Script is only for Ubuntu 20.04, 21.04, 21.10, 22.04, 22.10, 23.04 & 23.10 Only
Exiting...
------------------------------------------------------------------

daniel@dkdt:~/Store/Customization/GdmScript/ubuntu-gdm-set-background/ubuntu-gdm-set-background$ bash ubuntu-gdm-set-background --help

------------------------------------------------------------------
Sorry, Script is only for Ubuntu 20.04, 21.04, 21.10, 22.04, 22.10, 23.04 & 23.10 Only
Exiting...
------------------------------------------------------------------

daniel@dkdt:~/Store/Customization/GdmScript/ubuntu-gdm-set-background/ubuntu-gdm-set-background$
```

Also, how can I reset to default Ubuntu GDM login screen?

**Comment by PRATAP-KUMAR** [comment]
Hi Sorry to hear that.
Can you use ‘backup’ branch script.

If you want to go back to default ubuntu follow the instructions of trouble shoot from ‘backup’ branch help.

**Comment by PRATAP-KUMAR** [comment]
Hi @in4matix Here are the commands that can help to go back to original theme.

1. `update-alternatives --list gdm-theme.gresource`
2. `sudo update-alternatives --config gdm-theme.gresource` and then choose the number that has `.../Yaru/gnome-shell-theme.gresource`

Thanks

Example:
```
$ update-alternatives --list gdm-theme.gresource
/usr/share/gnome-shell/gnome-shell-theme.gresource
/usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource

$ update-alternatives --config gdm-theme.gresource 
There are 2 choices for the alternative gdm-theme.gresource (providing /usr/share/gnome-shell/gdm-theme.gresource).

  Selection    Path                                                           Priority   Status
------------------------------------------------------------
  0            /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource   15        auto mode
  1            /usr/share/gnome-shell/gnome-shell-theme.gresource              10        manual mode
* 2            /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource   15        manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
$ 
```

**Comment by sir-george2500** [comment]
I am encounter this same issue Ubuntu 23.10

**Comment by PRATAP-KUMAR** [comment]
Hi @sergiocbueno, I request you to unset evertything for Ubuntu 23.10 and use the gdm-extension as mentioned in the README

**Comment by in4matix** [comment]
Hi Pratap,
The backup branch script produces the same results as the main branch script...
Thanks for the reset instructions, that worked.
Are you planning on making the gdm-extension available for Ubuntu 22 ?

**Comment by PRATAP-KUMAR** [comment]
not rite now as I feel installing 22.04 is a tedious task for my present situation, but if number of users requests it, I may definitely get interest to do. I am waiting for users response for this extension on 23.10. It really helps to avoid recompiling of gresources like this script. Since `backup` branch script is also not worked that means, 22.04 source code might have changed. I am dual booting Arch Linux and Ubuntu 23.10. Not able to install 22.04 to investigate this.

**Comment by PRATAP-KUMAR** [comment]
Hi @in4matix I forgot to ask you, have you tried this?

**Comment by in4matix** [comment]
No, it's too complicated and I'm too stupid. Have found this:
[](https://c-nergy.be/blog/?p=19236)

**Comment by PRATAP-KUMAR** [comment]
Wow thats a wonderful script

**Comment by PRATAP-KUMAR** [comment]
@in4matix How are you doing?
can you try this extension for customizing gdm login screen https://github.com/PRATAP-KUMAR/gdm-exntension

Thanks

**Comment by PRATAP-KUMAR** [comment]
for Ubuntu 22 LTS Support migrated to [gdm-extension](https://github.com/PRATAP-KUMAR/gdm-extensions)

**Comment by in4matix** [comment]
Hi,
The link seems to be broken?

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/gdm-extension

Thanks for pointing out
