### ISSUE TITLE
Just to confirm: no support for 18.04?

### ISSUE THREAD

**Issue by NouGithub** [PRATAP-KUMAR/ubuntu-gdm-set-background#5]
Thank you for your script.

I've had no luck easily (successfully) changing my 18.04 login screen and I came across your github. I just wanted to confirm that is not compatible with 18.04?

Many thanks

**Comment by PRATAP-KUMAR** [comment]
Hi it is not compatible.

**Comment by NouGithub** [comment]
Thank you for your speedy and complete reply.  Bookmarked your project for when I upgrade.
