### ISSUE TITLE
Flash of Purple at login

### ISSUE THREAD

**Issue by riquezjp** [PRATAP-KUMAR/ubuntu-gdm-set-background#8]
I expect it is a side effect that can't be avoided: After submitting the password the background shows Purple for a moment before the desktop appears.
Its a shame the purple cant be replaced completely, but I do appreciate this clever script.

**Comment by PRATAP-KUMAR** [comment]
@riquezjp the purple color that you mention is a part of Gnome Desktop.. the script part cant tweak that purple color but there is a gnome extension that can hide the purple color https://extensions.gnome.org/extension/3037/good-bye-gdm-flick/

I am sorry for late reply.

**Comment by xpww** [comment]
> @riquezjp the purple color that you mention is a part of Gnome Desktop.. the script part cant tweak that purple color but there is a gnome extension that can hide the purple color https://extensions.gnome.org/extension/3037/good-bye-gdm-flick/
> 
> I am sorry for late reply.

hi!Now that this script has disappeared and cannot be obtained in the gnome store, is there any other way?

**Comment by PRATAP-KUMAR** [comment]
Hi what's your GNOME version? I have disabled that extension bcoz it's not updated for newer GNOME versions.

**Comment by xpww** [comment]
> Hi what's your GNOME version? I have disabled that extension bcoz it's not updated for newer GNOME versions.

It's 3.36.8 and my ubuntu is 20.04 (╥﹏╥)

**Comment by PRATAP-KUMAR** [comment]
https://extensions.gnome.org/extension/3037/good-bye-gdm-flick/ can you try this now

**Comment by xpww** [comment]
> https://extensions.gnome.org/extension/3037/good-bye-gdm-flick/ can you try this now

Thank you! The purple has now turned black, which is great. The purple used to be blinding.

**Comment by PRATAP-KUMAR** [comment]
I would like to disable this extension from gnome-extensions. Please make a copy of it.

Thanks.
